[database]
    [database.ppt]
        [database.ppt.master]
            url = "root:root@tcp(localhost:3306)/ppt?charset=utf8&parseTime=True&loc=Local"
            type = "mysql"
            idleNum = "1"
            openNum = "10"
            debug = true
        [database.ppt.slave]
            url = [
                "root:root@tcp(localhost:3306)/ppt?charset=utf8&parseTime=True&loc=Local"
            ]
            type = "mysql"
            idleNum = "3"
            openNum = "10"
            debug = true
    [database.pay]
        [database.pay.master]
            url = "root:root@tcp(localhost:3306)/pay?charset=utf8&parseTime=True&loc=Local"
            type = "mysql"
            idleNum = "1"
            openNum = "10"
            debug = true
        [database.pay.slave]
            url = [
                "root:root@tcp(localhost:3306)/pay?charset=utf8&parseTime=True&loc=Local"
            ]
            type = "mysql"
            idleNum = "3"
            openNum = "10"
            debug = true
    [database.joe]
        [database.joe.master]
            url = "root:root@tcp(localhost:3306)/joe?charset=utf8&parseTime=True&loc=Local"
            type = "mysql"
            idleNum = "1"
            openNum = "10"
            debug = true
        [database.joe.slave]
            url = [
                "root:root@tcp(localhost:3306)/joe?charset=utf8&parseTime=True&loc=Local"
            ]
            type = "mysql"
            idleNum = "3"
            openNum = "10"
            debug = true

[cache]
    [cache.redis]
        [cache.redis.ppt]
            host = "127.0.0.1"
            pwd = ""
            ttl = "30"
            db = "5"
            port = "6379"
        [cache.redis.pay]
            host = "127.0.0.1"
            pwd = ""
            ttl = "30"
            db = "3"
            port = "6379"
        [cache.redis.joe]
            host = "127.0.0.1"
            pwd = ""
            ttl = "30"
            db = "1"
            port = "6379"